version: '2'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress1
      WORDPRESS_DB_PASSWORD: wordpress1
      WORDPRESS_DB_NAME: wordpress1

  db:
    image: mariadb:10.2
    restart: always
    environment:
      MYSQL_DATABASE: wordpress1
      MYSQL_USER: wordpress1
      MYSQL_PASSWORD: wordpress1
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

